Fixed logic to open an external url
shopgate-professional-services/ext-pdp-accordion pull request #4
Opened 2020-02-27 13:59 UTC by Phmank

2020-02-27 16:14 UTC, Carsten89 requested changes

2020-02-27 16:14 UTC, Carsten89 commented on CHANGELOG.md
> +# [1.3.0] - 2020-02-26
```suggestion
# [1.3.1] - 2020-02-26
```
because only bugfixes and no new features

2020-02-27 16:14 UTC, Carsten89 commented on CHANGELOG.md
> +# [1.3.0] - 2020-02-26
```suggestion
# [1.2.1] - 2020-02-26
```
because only bugfixes and no new features

2020-02-28 07:26 UTC, Phmank commented on CHANGELOG.md
> +# [1.3.0] - 2020-02-26
done (1.2.1)

2020-02-28 07:26 UTC, Phmank commented on CHANGELOG.md
> +# [1.3.0] - 2020-02-26
done

2020-02-28 07:28 UTC, merged